name: CI

on:
  push:
    branches:
      - master

jobs:

  build-server:
    name: 'Build and Push Server'
    runs-on: ubuntu-latest
    defaults:
      run:  
        working-directory: ../../server
    steps:
    - uses: actions/checkout@v4

    - name: List files in server directory  # Debugging step
      run: ls -la ../../server  # Check contents of the server folder

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm npm test
      
  # build-web:
  #   name: 'Build and Push Web'
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:  
  #       working-directory: ../../web
  #   steps:
  #   - uses: actions/checkout@v4
