name: CI

on:
  push:
    branches:
      - main

jobs:

  build:
    name: 'Build and Push Server'
    runs-on: ubuntu-latest
    defaults:
      run:  
        working-directory: ../../server
    steps:
    - uses: actions/checkout@v4

  build:
    name: 'Build and Push Web'
    runs-on: ubuntu-latest
    defaults:
      run:  
        working-directory: ../../web
    steps:
    - uses: actions/checkout@v4